version: '3'
services:
  app:
    build:
      context: .
    environment:
        DATABASE_URL: database.jandolejs.cz
        DATABASE_NAME: cdn
        DATABASE_USER: cdn
        DATABASE_PASS: cdn
    networks:
      - other
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`www.${PROJECT_BASE_URL}`) || Host(`${PROJECT_BASE_URL}`)"
        - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"


networks:
  other:
    name: other
    external: true
