version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    networks:
      - other
    volumes:
        - ./.flaskenv:/app/.flaskenv
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`www.${PROJECT_BASE_URL}`) || Host(`${PROJECT_BASE_URL}`)"
        - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"


networks:
  other:
    name: other
    external: true
